import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import  Navbar from '@/components/Navbar'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Brincando com o NextJs',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar></Navbar>
        {children}
        
      </body>
    </html>
  )
}
